### ISSUE TITLE
Request for 32-bit builds of kernel-pf

### ISSUE THREAD

**Issue by avillacis** [encounter/fedora-kernel-pf#2]
There are still 32-bit-only Fedora 24 systems out there that could also benefit from a kernel-pf build with BFS and BFQ. For example, my Acer Aspire One ZG5...

**Comment by encounter** [comment]
Added i386 to the main kernel-pf copr for both F23 and F24, packages are building now.

Check the build status here: https://copr.fedorainfracloud.org/coprs/encounter/kernel-pf/monitor/detailed
