### ISSUE TITLE
F23 x86 - Complete FREEZE

### ISSUE THREAD

**Issue by presianbg** [encounter/fedora-kernel-pf#3]
Hello,

I'm experiencing complete freezes with the latest build - 4.7.3-101.pf.haswell.fc23 on my Fedora 23.

I'm using bumblebee (do not know if that is related) and cinnamon. The complete system freeze is happening right after i try press the login button (lightdm as DM). 

Everything works perfect with kernel-4.6.6-201.pf.haswell.fc23.x86_64.

Would you be so kind to look at this? 

Many thanks in advance.

**Comment by presianbg** [comment]
All fine with the latest build - 4.7.10-101.pf.haswell.fc23.x86_64

**Comment by encounter** [comment]
Have you tried another 32-bit build, or are you only running 64-bit now?

**Comment by presianbg** [comment]
only 64 bit, but as I said everything is fine with latest build! Thanks for your work :)
