### ISSUE TITLE
MUQSS not enabled

### ISSUE THREAD

**Issue by presianbg** [encounter/fedora-kernel-pf#4]
Hi,

Why MUQSS is not enabled in the latest conf ?

Best Regards,
Presian

**Comment by encounter** [comment]
MuQSS isn't quite stable enough to replace BFS, but it's getting there quickly. I'll likely enable it soon.

**Comment by encounter** [comment]
The latest builds of the kernel (4.8.13) enable MuQSS. 

Let me know if you find any issues.
